version: "3.8"
services:
  db:
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: Games4Trade
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  api:
    build:
      context: "Web Api/Games4Trade"
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ApplicationContext: Server=db;Port=5432; User Id=${DB_USER}; Password=${DB_PASSWORD}; Database=Games4Trade;
  client:
    build:
      context: "Client/Games4Trade"
      dockerfile: Dockerfile
    ports:
      - "80:80"