version: "3.8"
services:
  minio:
    image: minio/minio
  db:
    image: postgres:latest
    volumes: 
      - postgres_data:/var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
  api:
    depends_on:
     - db
  client:

volumes: 
  postgres_data:
  minioData:
