version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: Games4Trade
      POSTGRES_PASSWORD: admin
    volumes: 
      - postgres_data:/var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
  api:
    depends_on:
     - db
    build:
      context: "Web Api/Games4Trade"
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ApplicationContext: Server=db;Port=5432; User Id=postgres; Password=admin; Database=Games4Trade;

volumes: 
  postgres_data:
