version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: Games4Trade
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - postgres_data:/var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
  api:
    depends_on:
     - db
    build:
      context: "Web Api/Games4Trade"
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ApplicationContext: Server=db;Port=5432; User Id=${DB_USER}; Password=${DB_PASSWORD}; Database=Games4Trade;
  client:
    depends_on: 
      - api
    build:
      context: "Client/Games4Trade"
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes: 
  postgres_data:
