// <auto-generated />
using System;
using Games4TradeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Games4TradeAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180909140221_user system relationship")]
    partial class usersystemrelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Games4Trade.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("Now()");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Games4Trade.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Games4Trade.Models.ObservedUsersRelationship", b =>
                {
                    b.Property<int>("ObservingUserId");

                    b.Property<int>("ObservedUserId");

                    b.HasKey("ObservingUserId", "ObservedUserId");

                    b.HasIndex("ObservedUserId");

                    b.ToTable("ObservedUsersRelationship");
                });

            modelBuilder.Entity("Games4Trade.Models.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer", "Model");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("Games4Trade.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<string>("RecoveryAddress")
                        .HasMaxLength(32);

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("'User'")
                        .HasMaxLength(8);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Games4Trade.Models.UserLikedGenre", b =>
                {
                    b.Property<int>("GenreId");

                    b.Property<int>("UserId");

                    b.HasKey("GenreId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGenreRelationship");
                });

            modelBuilder.Entity("Games4Trade.Models.UserOwnedSystem", b =>
                {
                    b.Property<int>("SystemId");

                    b.Property<int>("UserId");

                    b.HasKey("SystemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSystemRelationship");
                });

            modelBuilder.Entity("Games4Trade.Models.Announcement", b =>
                {
                    b.HasOne("Games4Trade.Models.User", "User")
                        .WithMany("Announcements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Games4Trade.Models.ObservedUsersRelationship", b =>
                {
                    b.HasOne("Games4Trade.Models.User", "ObservedUser")
                        .WithMany("ObservedUsers")
                        .HasForeignKey("ObservedUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Games4Trade.Models.User", "ObservingUser")
                        .WithMany("ObservingUsers")
                        .HasForeignKey("ObservingUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Games4Trade.Models.UserLikedGenre", b =>
                {
                    b.HasOne("Games4Trade.Models.Genre", "Genre")
                        .WithMany("LikedByUsers")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Games4Trade.Models.User", "User")
                        .WithMany("LikedGenres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Games4Trade.Models.UserOwnedSystem", b =>
                {
                    b.HasOne("Games4Trade.Models.System", "System")
                        .WithMany("OwnedByUsers")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Games4Trade.Models.User", "User")
                        .WithMany("OwnedSystems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
