// <auto-generated />
using System;
using Games4TradeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Games4TradeAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260808113723_ReconcileEfCore10Model")]
    partial class ReconcileEfCore10Model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Games4TradeAPI.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("Now()");

                    b.Property<bool>("ExchangeActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<bool>("ShowEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowPhone")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.AdvertisementItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateReleased")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<int>("SystemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId")
                        .IsUnique();

                    b.HasIndex("StateId");

                    b.HasIndex("SystemId");

                    b.ToTable("AdvertisementItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AdvertisementItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("Now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("Now()");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.ObservedUsersRelationship", b =>
                {
                    b.Property<int>("ObservingUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ObservedUserId")
                        .HasColumnType("integer");

                    b.HasKey("ObservingUserId", "ObservedUserId");

                    b.HasIndex("ObservedUserId");

                    b.ToTable("ObservedUsersRelationship");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvertisementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("Now()");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "PAL"
                        },
                        new
                        {
                            Id = 2,
                            Value = "NTSC"
                        },
                        new
                        {
                            Id = 3,
                            Value = "INNY"
                        },
                        new
                        {
                            Id = 4,
                            Value = "MULTI"
                        });
                });

            modelBuilder.Entity("Games4TradeAPI.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Nowy"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Używany"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Uszkodzony"
                        });
                });

            modelBuilder.Entity("Games4TradeAPI.Models.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer", "Model");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<string>("RecoveryAddress")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValueSql("'User'");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.UserLikedGenre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("GenreId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGenreRelationship");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.UserOwnedSystem", b =>
                {
                    b.Property<int>("SystemId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SystemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSystemRelationship");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Accessory", b =>
                {
                    b.HasBaseType("Games4TradeAPI.Models.AdvertisementItem");

                    b.Property<string>("AccessoryManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("AccessoryModel")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Accessory");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Console", b =>
                {
                    b.HasBaseType("Games4TradeAPI.Models.AdvertisementItem");

                    b.Property<int?>("ConsoleRegionId")
                        .HasColumnType("integer");

                    b.HasIndex("ConsoleRegionId");

                    b.HasDiscriminator().HasValue("Console");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Game", b =>
                {
                    b.HasBaseType("Games4TradeAPI.Models.AdvertisementItem");

                    b.Property<string>("Developer")
                        .HasColumnType("text");

                    b.Property<int?>("GameRegionId")
                        .HasColumnType("integer");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer");

                    b.HasIndex("GameRegionId");

                    b.HasIndex("GenreId");

                    b.HasDiscriminator().HasValue("Game");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Advertisement", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.User", "User")
                        .WithMany("Advertisements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.AdvertisementItem", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.Advertisement", "Advertisement")
                        .WithOne("Item")
                        .HasForeignKey("Games4TradeAPI.Models.AdvertisementItem", "AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Games4TradeAPI.Models.State", "State")
                        .WithMany("AdvertisementItems")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Games4TradeAPI.Models.System", "System")
                        .WithMany("AdvertisementItems")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("State");

                    b.Navigation("System");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Announcement", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.User", "User")
                        .WithMany("Announcements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Message", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.User", "Receiver")
                        .WithMany("MessagesRecived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Games4TradeAPI.Models.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.ObservedUsersRelationship", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.User", "ObservedUser")
                        .WithMany("ObservedUsers")
                        .HasForeignKey("ObservedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Games4TradeAPI.Models.User", "ObservingUser")
                        .WithMany("ObservingUsers")
                        .HasForeignKey("ObservingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObservedUser");

                    b.Navigation("ObservingUser");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Photo", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.Advertisement", "Advertisement")
                        .WithMany("Photos")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.User", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.Photo", "Photo")
                        .WithOne("User")
                        .HasForeignKey("Games4TradeAPI.Models.User", "PhotoId");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.UserLikedGenre", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.Genre", "Genre")
                        .WithMany("LikedByUsers")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Games4TradeAPI.Models.User", "User")
                        .WithMany("LikedGenres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.UserOwnedSystem", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.System", "System")
                        .WithMany("OwnedByUsers")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Games4TradeAPI.Models.User", "User")
                        .WithMany("OwnedSystems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Console", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.Region", "ConsoleRegion")
                        .WithMany("Consoles")
                        .HasForeignKey("ConsoleRegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ConsoleRegion");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Game", b =>
                {
                    b.HasOne("Games4TradeAPI.Models.Region", "GameRegion")
                        .WithMany("Games")
                        .HasForeignKey("GameRegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Games4TradeAPI.Models.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GameRegion");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Advertisement", b =>
                {
                    b.Navigation("Item")
                        .IsRequired();

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Genre", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("LikedByUsers");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Photo", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Games4TradeAPI.Models.Region", b =>
                {
                    b.Navigation("Consoles");

                    b.Navigation("Games");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.State", b =>
                {
                    b.Navigation("AdvertisementItems");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.System", b =>
                {
                    b.Navigation("AdvertisementItems");

                    b.Navigation("OwnedByUsers");
                });

            modelBuilder.Entity("Games4TradeAPI.Models.User", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Announcements");

                    b.Navigation("LikedGenres");

                    b.Navigation("MessagesRecived");

                    b.Navigation("MessagesSent");

                    b.Navigation("ObservedUsers");

                    b.Navigation("ObservingUsers");

                    b.Navigation("OwnedSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
